#!/bin/sh

docmd() { (set -x; "$@"); }

main()
{
    case ${EUID-${UID-`id -u`}} in
        0 ) : ;;
        * ) exec sudo "$0" "$@" || exit $? ;;
    esac

    systemctl daemon-reload
    vmware-ws-ctl system stop

    # If vmware.service file exists, do not use chkconfig.
    # This is only to disable legacy sysv scripts.
    if ! [ -f /etc/systemd/system/vmware.service ]; then
        svcs='vmware
              vmamqpd
              vmware-USBArbitrator
              vmware-workstation-server
              vmware-wsx-server
             '

        for svc in $svcs ; do
            test -f /etc/rc.d/init.d/$svc ||
                test -f /etc/init.d/$svc  ||
                continue
            docmd chkconfig $svc off
        done
    fi

    vcs_files='vmware/networking
               vmware/vmnet8/dhcpd/dhcpd.conf
               vmware/vmnet8/nat/nat.conf
               vmware/vmnet8/nat.mac
              '
    if [ -d /etc/.git ]; then
        git -C /etc revert-file -v $vcs_files
    elif [ -d /etc/.hg ]; then
        (cd /etc && hg-revert -v $vcs_files)
    fi

    sed -i.bak \
        -e '/^accept.*EULA/s/none/yes/' \
        -e '/^installerDefaults.*initialized/s/none/yes/' \
        /etc/vmware/config
}

main "$@"

# eof
