#!/bin/sh
# $Id: vmware-finish-upgrade,v 1.2 2014/08/21 05:12:01 friedman Exp $

docmd()
{
    echo + "$@" 1>&2
    "$@"
}

main()
{
    case ${EUID-${UID-`id -u`}} in
        0 ) : ;;
        * ) exec sudo "$0" "$@" || exit $? ;;
    esac

    vmware-ws-ctl system stop

    svcs='vmware
          vmamqpd
          vmware-USBArbitrator
          vmware-workstation-server
          vmware-wsx-server
         '

    for svc in $svcs ; do
        test -f /etc/rc.d/init.d/$svc ||
            test -f /etc/init.d/$svc  ||
            continue
        docmd chkconfig $svc off
    done

    (   cd /etc &&
            hg-revert -v vmware/vmnet8/dhcpd/dhcpd.conf \
                         vmware/vmnet8/nat/nat.conf
    )
}

main "$@"

# eof
