#!/bin/sh
# $Id$

# Find console executable in Firefox plugins.
vmrc=$(find "$HOME/.mozilla/firefox" -name vmware-vmrc -type f -perm -111 \
        | sed -e '/plugins\/vmware-vmrc/!d' -e q)
test -x "$vmrc" || exit 1

export GDK_NATIVE_WINDOWS=true

#export VMWARE_USE_SHIPPED_GTK=yes
#vmrcdir=${vmrc%/*}
#cd ${vmrcdir:-.} || exit $?

exec "$vmrc" "$@"

# eof
