#!/bin/bash
# $Id: vmware-vmnet-restore,v 1.1 2008/01/30 22:15:50 friedman Exp $

find /etc/vmware/vmnet* -name '*,v' -print \
 | sort \
 | while read v ; do
     w=${v##*/}     # basename
     w=${w%,v}      # strip off ,v suffix

     wd=${v%/*}     # dirname
     wd=${wd%/RCS}  # strip off RCS dir if any

     rm -f $wd/$w \
      && co -M $wd/$w \
      && find $wd \( -name "$w.old.*" -o -name "$w.bak" \) \
                  -printf "Removing %p\n" \
                  -delete
   done

# eof
