#!/bin/sh
# $Id$

docmd()
{
    echo + "$@" 1>&2
    "$@"
}

main()
{
    case ${EUID-${UID-`id -u`}} in
        0 ) : ;;
        * ) exec sudo "$0" "$@" || exit $? ;;
    esac

    vmware-ws-ctl system stop

    svcs='vmware
          vmamqpd
          vmware-USBArbitrator
          vmware-workstation-server
         '

    for svc in $svcs ; do
        docmd chkconfig $svc off
    done

    hg-revert -v /etc/vmware/vmnet8/dhcpd/dhcpd.conf \
                 /etc/vmware/vmnet8/nat/nat.conf
}

main "$@"

# eof
