#!/bin/sh

exec qemu-img create               \
     -f vmdk                       \
     -o hwversion=7                \
     -o adapter_type=lsilogic      \
     -o subformat=monolithicSparse \
     "$@"

# eof
