#!/usr/bin/env python
# vsphere-guest-command --- run command in virtual machine via guest tools

# Author: Noah Friedman <friedman@splode.com>
# Created: 2018-08-20
# Public domain

# $Id$

# Commentary:
# Code:

from   __future__ import print_function
import vspherelib     as vsl
import os
import sys

vim = vsl.vim
vsl.timestamp_format = '[%Y:%M:%S%f]'

def get_args():
    p = vsl.ArgumentParser( loadrc=True )
    p.add( '-U', '--guest-username',  required=True )
    p.add( '-P', '--guest-password',  required=True )
    p.add( '-F', '--script-file',                    default=None )
    p.add( '-O', '--no-output',       dest='output', default=True,   action='store_false' )
    p.add( '-E', '--separate-stderr',                default=False,  action='store_true' )
    p.add( '-W', '--no-wait',         dest='wait',   default=True,   action='store_false' )
    p.add( '-C', '--cwd',                            default=None )
    p.add( '-v', '--verbose',                        default=False,  action='store_true' )
    p.add( '-L', '--local-environ',                  default=False,  action='store_true' )
    p.add( '-m', '--multi-command',   dest='multi',  default=False,  action='store_true' )
    p.add( 'vm',   nargs=1,                          help='VM name' )
    p.add( 'cmd',  nargs='*',                        help='Commands (one per arg)' )
    return p.parse()


def output_fixup( vop, s ):
    # Some windows commands (e.g. wmic) output utf16.
    # Unfortunately this can be mixed with ascii,
    # so we can't convert the entire output using a proper codec.
    if vop.ostype is vsl.WinNT:
        fixups = [ ('\ufeff', ''),
                   ('\0',     ''),
                   ('\r\n',   '\n'), ]
        for f in fixups:
            s = s.replace( *f )
    return s


def err( vm, *args, **kwargs ):
    kwargs.setdefault( 'progname', None )
    s = kwargs.get( 'sep', ' ').join( args )
    vsl.printerr( vm.name, s, **kwargs )


def main():
    args = get_args()
    if (args.output or args.separate_stderr) and not args.wait:
        vsl.printerr( 'cannot use --no-wait unless output is disabled' )
        sys.exit( 1 )

    join_char = '\n' if args.multi else ' '
    pargs = { 'wait'            : args.wait,
              'script_file'     : args.script_file,
              'script'          : join_char.join( args.cmd ),
              'output'          : args.output,
              'separate_stderr' : args.separate_stderr,
              'cwd'             : args.cwd, }
    if args.local_environ:
        pargs[ 'environ' ] = os.environ

    vsi    = vsl.vmomiConnect( args )
    vmlist = vsi.find_vm( args.vm )

    exitstat = 0
    for vm in vmlist:
        if vm.config.template:
            err( vm, 'cannot run commands on template.' )
            continue
        elif vm.runtime.powerState in ('poweredOff', ):
            state = vm.runtime.powerState.lower().replace( 'd', 'd ', 1 )
            err( vm, 'cannot run command in', state, 'state' )
            continue

        vop  = vsi.vmguest_ops( vm,
                                username=args.guest_username,
                                password=args.guest_password )
        try:
            proc = vop.run( **pargs )
        except vim.fault.GuestOperationsFault as e:
            err( vm, e.msg )
            continue

        if len( vmlist ) > 1: print( vm.name )
        if not args.wait:
            continue
        if len( vmlist ) > 1: print( '-' * len( vm.name ) )

        res = proc.result
        if res.get( 'output' ):
            print( output_fixup( vop, res.output ))
        if res.get( 'stderr' ):
            print( output_fixup( vop, res.stderr ), file=sys.stderr )
        if args.verbose:
            print( '[Exit {}]'.format( str( res.exit )), file=sys.stderr )
            print( 'Started:', res.startTime, file=sys.stderr )
            print( 'Ended:  ', res.endTime,   file=sys.stderr )

        if len( vmlist ) > 1: print()
        exitstat = exitstat or res.exit

    sys.exit( exitstat )


if __name__ == '__main__':
    main()

# eof
