#!/usr/bin/env python
# $Id: vsphere-vm-list,v 1.1 2018/05/08 21:32:52 friedman Exp $

from   __future__ import print_function
from   pyVmomi    import vim
import vspherelib     as vsl

def get_args():
    parser = vsl.ArgumentParser()
    args = parser.parse_args()
    return args

def main():
    args = get_args()
    vsi  = vsl.vmomiConnector( args )

    vmlist = vsi.get_obj_props( [vim.VirtualMachine], [ 'name' ] )
    namelist = [ vm[ 'name' ] for vm in vmlist ]
    namelist.sort()

    for name in namelist:
        print( name )

if __name__ == '__main__':
    main()

# eof
