#!/usr/bin/env python
# $Id: vsphere-vm-list,v 1.2 2018/07/19 00:48:39 friedman Exp $

from   __future__ import print_function
from   pyVmomi    import vim
import vspherelib     as vsl

def main():
    args = vsl.ArgumentParser().parse_args()
    vsi  = vsl.vmomiConnect( args )

    vmlist = vsi.get_obj_props( [vim.VirtualMachine], [ 'name' ] )
    namelist = [ vm[ 'name' ] for vm in vmlist ]
    namelist.sort()

    for name in namelist:
        print( name )

if __name__ == '__main__':
    main()

# eof
