#!/usr/bin/env python
# $Id: vsphere-vm-destroy,v 1.1 2018/05/08 21:32:52 friedman Exp $

from   __future__ import print_function
import vspherelib     as vsl

import os
import sys

def get_args():
    parser = vsl.ArgumentParser()
    parser.add_argument( 'vm', nargs='*', help='VM names' )
    args = parser.parse_args()
    if not args.vm:
        printerr( 'Specify VM names' )
        sys.exit (1)
    return args

def power_off( vsi, vm ):
    if vm.runtime.powerState == 'poweredOn':
        print( 'Powering off {}... '.format( vm.name ), end='' )
        task = vm.PowerOff()
        succ = vsi.taskwait( task, printsucc=False )
        if not succ:
            return False
        print( 'success' )
    return True

def nuke( vsi, vm ):
    print( '{}: Unregistering vm and deleting data... '.format( vm.name ), end='' )
    task = vm.Destroy()
    succ = vsi.taskwait( task, printsucc=False )
    if not succ:
        return False
    print( 'success' )
    return True

def main():
    args = get_args()
    vsi  = vsl.vmomiConnector( args )

    vmlist = vsi.find_vm( args.vm )
    for vm in vmlist:
        if vsl.yes_or_no_p( 'Really destroy {}?'.format( vm.name ), default=False ):
            power_off( vsi, vm ) and nuke( vsi, vm )
        else:
            print( "I could tell you weren't really serious." )

if __name__ == "__main__":
    main()

# eof
